---
version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "Type: Chore"

  - package-ecosystem: bundler
    directory: "/"
    target-branch: "18-stable"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "Type: Chore"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    labels:
      - "Type: Chore"
