---
version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "Type: Chore"
    # don't automatically rebase on every single time we're out of date with
    # base (whith is always) because it kills CI capacity
    rebase-strategy: disabled
    ignore:
      - dependency-name: "ffi-yajl"
        # Locking to 2.x until ffi-yajl 3.x gets the allocator fix https://github.com/chef/ffi-yajl/pull/126 fail-after:2026-08-22
        versions: ["3.x"]

  - package-ecosystem: bundler
    directory: "/"
    target-branch: "18-stable"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "Type: Chore"
    # don't automatically rebase on every single time we're out of date with
    # base (whith is always) because it kills CI capacity
    rebase-strategy: disabled

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    labels:
      - "Type: Chore"
    # don't automatically rebase on every single time we're out of date with
    # base (whith is always) because it kills CI capacity
    rebase-strategy: disabled
