require: rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - "spec/data/**/*"
    - "vendor/**/*"
    - "pkg/**/*"

# these have shellout examples that need to have the tabs that come with the shellout
Layout/IndentationStyle:
  Exclude:
    - "lib/ohai/plugins/mono.rb"
    - "lib/ohai/plugins/darwin/hardware.rb"

Performance/Caller:
  Enabled: false

Performance/CollectionLiteralInLoop:
  Enabled: false