AllCops:
  Exclude:
    - "spec/data/**/*"
    - "vendor/**/*"
    - "pkg/**/*"

# these have shellout examples that need to have the tabs that come with the shellout
Layout/Tab:
  Exclude:
    - "lib/ohai/plugins/mono.rb"
    - "lib/ohai/plugins/darwin/hardware.rb"

Performance/UnneededSort:
  Enabled: true
